const express=require('express');
const router=express.Router();
const usersController=require("../controllers/usersController");
router.get('/profile',usersController.profile);
router.get('/dp',usersController.dp);
router.get('/signup',usersController.signup);
router.get('/signin',usersController.signin);
router.post('/create',usersController.create);
router.post('/createSession',usersController.createSession);
module.exports=router;